/*
 *
 * AuthenPage constants
 *
 */
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const SETTING_UPDATE = 'SETTING_UPDATE'
export const SETTING_UPDATE_SUCCESS = 'SETTING_UPDATE_SUCCESS'
