/*
 *
 * ArticlesPages constants
 *
 */

export const DEFAULT_ACTION = 'app/ArticlesPages/DEFAULT_ACTION';
export const GET_ARTICLE_REQUEST = 'GET_ARTICLE_REQUEST';
export const GET_ARTICLE_SUCCESS = 'GET_ARTICLE_SUCCESS';

export const UPDATE_ARTICLE_REQUEST = 'UPDATE_ARTICLE_REQUEST';
export const UPDATE_ARTICLE_SUCCESS = 'UPDATE_ARTICLE_SUCCESS';

export const GET_COMMENTS_ARTICLE_REQUEST = 'GET_COMMENTS_ARTICLE_REQUEST';
export const GET_COMMENTS_ARTICLE_SUCCESS = 'GET_COMMENTS_ARTICLE_SUCCESS';
