/*
 *
 * ProfilePage constants
 *
 */

export const DEFAULT_ACTION = 'app/ProfilePage/DEFAULT_ACTION';

export const PROFILE_GET_PROFILE_REQUEST = 'PROFILE_GET_PROFILE_REQUEST';
export const PROFILE_GET_PROFILE_SUCCESS = 'PROFILE_GET_PROFILE_SUCCESS';

export const PROFILE_TOGGLE_FOLLOW_USER_REQUEST = 'PROFILE_TOGGLE_FOLLOW_USER';
export const PROFILE_TOGGLE_FOLLOW_USER_SUCCESS = 'PROFILE_TOGGLE_FOLLOW_USER_SUCCESS';
